### PR TITLE
[enhancement] Add UNKNOWN as Device monitoring status

### LINKED ISSUE #2: Device monitoring status: add UNKNOWN
We should add a default monitoring status which should become the new default.
As soon as a device is added the system doesn't know if the device is reachable yet.
We may call this status "unknown" or something similar.

### PR DESCRIPTION
**Pull request by nepython**
Closes #2

### CODE REVIEW

**Comment by nepython** [comment]
Coverage check successful, all 3 relevant lines covered
Isort check successful
Flake8 check successful

**Comment by TheOneAboveAllTitan** [comment]
Please add documentation for this. :smile:

**Comment by nepython** [comment]
@TheOneAboveAllTitan thanks for the suggestion, I have added it now :smiley:

**Comment by nepython** [comment]
@nemesisdesign, it's done :smiley:

**Pull request merged**
