### PR TITLE
[refactor] Load BaseDevice using swappable

### PR DESCRIPTION
**Pull request by nemesisdesign**
Temporary solution, may be obsoleted by
https://github.com/wq/django-swappable-models/pull/23

### CODE REVIEW

**Comment by nepython** [comment]
Seems a good fix :smiley:. Can we add a regression test to be sure that extended models will work nicely if it's not too difficult.

**Comment by nemesisdesign** [comment]
> Can we add a regression test to be sure that extended models will work nicely if it's not too difficult.

Any suggestion or idea on how to test this?

**Comment by nepython** [comment]
> > Can we add a regression test to be sure that extended models will work nicely if it's not too difficult.
> 
> Any suggestion or idea on how to test this?

Well, yes a very rough idea on how I would have approached it. We can test it as how `django` tests it.
1. We create a new `test_app` with a `models.py`, containing the extended model but we disable auto loading for the model (https://github.com/django/django/blob/master/tests/migrations/models.py#L37)
2. Override settings for `INSTALLED_APPS` and `EXTENDED_APPS` for the test
3. Now migrate the changes within the test (https://github.com/django/django/blob/master/tests/migrations/test_commands.py#L32).
4. Reload the apps
5. Check if the extended model can be imported safely.
6. Run reverse migrations on completion / failure

:warning: **IMHO it is not worth the effort** as it seems now. :sweat_smile:

**Comment by nemesisdesign** [comment]
>  **IMHO it is not worth the effort** as it seems now.

I agree, it's a lot of code for not much added benefit for us.
Let's merge the way it is, if in the future we feel the need to add another test we will.

**Pull request merged**
