### PR TITLE
[WIP] [bug] Avoid race condition in test_wifi_hostapd

### LINKED ISSUE #7: [bug] test_wifi_hostapd is failing
**test_wifi_hostapd** is currently failing almost everytime on my end and occasionally on @nemesisdesign's end. 
It might be a local problem and might vary from PC to PC as can be concluded from above.
The full stack trace of the failing test is:
```
Traceback (most recent call last):
  File "/home/hardik/openwisp/openwisp-monitoring/openwisp_monitoring/monitoring/tests/test_graphs.py", line 242, in test_wifi_hostapd
    self.assertEqual(data['traces'][0][1][-10:], [0, 2, 2, 2, 2, 2, 2, 2, 2, 4])
AssertionError: Lists differ: [0, 2, 2, 2, 2, 2, 1, 2, 1, 4] != [0, 2, 2, 2, 2, 2, 2, 2, 2, 4]

First differing element 6:
1
2

- [0, 2, 2, 2, 2, 2, 1, 2, 1, 4]
?                    ---   ^

+ [0, 2, 2, 2, 2, 2, 2, 2, 2, 4]
?                       ^ +++
```

**Few additional details**
* OS : Ubuntu 18.04 LTS
* I am running this in a virtual environment with all dependencies installed.
* The list being generated is not the same in every run and this should not be happening.
* This is the only failing test currently in this module.

### PR DESCRIPTION
**Pull request by nepython**
Closes #7

### CODE REVIEW

**Comment by nepython** [comment]
@nemesisdesign the test was failing due to a race condition, I tested it multiple times and it is now passing on all occasions. After this and adding InfluxDB setup in travis maybe it could be activated for best as per @TheOneAboveAllTitan's suggestion :smile:

**Comment by TheOneAboveAllTitan** [comment]
It failed for me. :sweat_smile: 
```
======================================================================
FAIL: test_wifi_hostapd (openwisp_monitoring.monitoring.tests.test_graphs.TestGraphs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/openwisp/openwisp/openwisp-monitoring/openwisp_monitoring/monitoring/tests/test_graphs.py", line 242, in test_wifi_hostapd
    self.assertEqual(data['traces'][0][1][-10:], [0, 2, 2, 2, 2, 2, 2, 2, 2, 4])
AssertionError: Lists differ: [0, 2, 2, 2, 2, 2, 2, 2, 2, 2] != [0, 2, 2, 2, 2, 2, 2, 2, 2, 4]

First differing element 9:
2
4

- [0, 2, 2, 2, 2, 2, 2, 2, 2, 2]
?                             ^

+ [0, 2, 2, 2, 2, 2, 2, 2, 2, 4]
?                             ^


----------------------------------------------------------------------
Ran 121 tests in 27.052s

FAILED (failures=1)
Destroying test database for alias 'default'...
```

**Comment by nepython** [comment]
@TheOneAboveAllTitan thank you very much for trying it out, I checked on another pc and yes it failed occasionally on it too. This is not a fix them as it should pass across all systems. I am now checking out **write_points** method which is also used generally and is well documented. Thanks again for notifying, it did help :smiley:

**Comment by nepython** [comment]
>Tested it a few times and always failing with the latest commit in this branch.

I am unsure @nemesisdesign, let me try out few features of InfluxDB like **write_points** instead of **write** which is currently being used and check if the test passes.

**Comment by nepython** [comment]
Closing it for now as the tests seem to pass on travis. I will wait for a while before closing the issue just to be sure of it :smile:

**Pull request closed without merging**
