### PR TITLE
[schema] Improved consistency of properties

### LINKED ISSUE #182: [schema] Improve consistency of some properties (mac/mac_address, ip/ip_address)
The NetJSON spec uses `mac` over `mac_address`, while in DHCP leases and neighbors we use `mac_address` and `ip_address`, we could make everything more consistent by just using `mac` and `ip`.

We'll have to update https://github.com/openwisp/lua-monitoring as well.

### PR DESCRIPTION
**Pull request by devkapilbansal**
Closes #182 

Checks:

- [x] I have manually tested the proposed changes

### CODE REVIEW

**Review by Purhan — CHANGES_REQUESTED** [review]
Please mention the issue in the PR description as well (https://github.com/openwisp/openwisp-monitoring/issues/182)

Also, consider turning your IDE's auto-formatter off. It has removed commas and broken lines in places where `openwisp-qa-format` wouldn't :smile:.

**Comment by devkapilbansal** [comment]
> Please mention the issue in the PR description as well (#182 
Thanks for reminding this.
Also, I am not using any other formatter other than `openwisp-qa-format`

**Comment by Purhan** [comment]
> Also @Purhan , I am not using any other formatter other than `openwisp-qa-format`

That's strange because running it on master doesn't change anything for me. It also affected migrations. Other than that, LGTM :smile:

**Comment by devkapilbansal** [comment]
> > Also @Purhan , I am not using any other formatter other than `openwisp-qa-format`
> 
> That's strange because running it on master doesn't change anything for me. It also affected migrations. Other than that, LGTM 😄



> > Also @Purhan , I am not using any other formatter other than `openwisp-qa-format`
> 
> That's strange because running it on master doesn't change anything for me. It also affected migrations. Other than that, LGTM 😄

Run them after making the first commit

**Comment by Purhan** [comment]
> Run them after making the first commit

<details> 
  <summary>Terminal Output</summary>

image

</details>


@devkapilbansal I cloned your branch and tested it offline, it didn't make any difference.

**Comment by devkapilbansal** [comment]
@Purhan may be due to different versions of `openwisp-utils`. I am using the latest one
<details>
<summary> Output </summary>

terminal</ul>
</details>

**Review by Purhan — APPROVED** [review]
> @Purhan may be due to different versions of `openwisp-utils`. I am using the latest one

@devkapilbansal  I see, that was quite strange.Thanks for clarifying :smile:

**Review by nemesisdesign — COMMENTED** [review]
Looks good, but haven't tested it yet.

Can anyone help to implement these changes also in https://github.com/openwisp/lua-monitoring please?

**Review by nemesisdesign — APPROVED** [review]
Tested with https://github.com/openwisp/lua-monitoring/pull/20/files :heavy_check_mark:

**Pull request merged**
