### PR TITLE
[change] Changed python version from 3.6 to 3.8 and 3.9 #323

### PR DESCRIPTION
**Pull request by harsh7in**
Checks:

- [ ] I have manually tested the proposed changes
- [ ] I have written new test cases to avoid regressions (if necessary)
- [ ] I have updated the documentation (e.g. README.rst)

### CODE REVIEW

**Comment by pandafy** [comment]
@nemesisdesign you will need to update list of required checks in the repository.

**Comment by atb00ker** [comment]
@pandafy Is there is something else that needs to be updated for the 3.6 test to go away? 
This problem is there in multiple such PRs! Are you aware of it?

**Comment by devkapilbansal** [comment]
> @pandafy Is there is something else that needs to be updated for the 3.6 test to go away? This problem is there in multiple such PRs! Are you aware of it?

Maybe the branch protection rules that @nemesisdesign commented about in one of the PR

**Comment by atb00ker** [comment]
> Maybe the branch protection rules that @nemesisdesign commented about in one of the PR

Oh, I thought that was only true for travis. 
This is not ideal frankly if we have to do everytime, need to come up with a more permanent solution!

**Pull request merged**
